GET http://localhost:8080/api/cart HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxMGQ0N2VkNjg4NDA1MzVlMDVkYjBjYSIsImVtYWlsIjoicnVqYUBob3RtYWlsLmNvbSJ9LCJpYXQiOjE2MjgzNDM3OTYsImV4cCI6MTYyODM2NTM5Nn0.jwGWAMYiF2RQhEQI74Ss6Hcfmugysa8uE2xiCKIq3CE
### Get user cart

POST http://localhost:8080/api/cart/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxMGQ0N2VkNjg4NDA1MzVlMDVkYjBjYSIsImVtYWlsIjoicnVqYUBob3RtYWlsLmNvbSJ9LCJpYXQiOjE2MjgzNDM3OTYsImV4cCI6MTYyODM2NTM5Nn0.jwGWAMYiF2RQhEQI74Ss6Hcfmugysa8uE2xiCKIq3CE

  {
    "productId": "610e8e09e3b26b2a80dac0eb",
    "quantity": "20"
  }
### Add, update products in cart

POST http://localhost:8080/api/cart/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxMGQ0N2VkNjg4NDA1MzVlMDVkYjBjYSIsImVtYWlsIjoicnVqYUBob3RtYWlsLmNvbSJ9LCJpYXQiOjE2MjgzNDM3OTYsImV4cCI6MTYyODM2NTM5Nn0.jwGWAMYiF2RQhEQI74Ss6Hcfmugysa8uE2xiCKIq3CE

  {
    "productId": "610e8e09e3b26b2a80dac0eb",
    "quantity": "15"
  }
### 

POST http://localhost:8080/api/cart/submit HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxMGQ0N2VkNjg4NDA1MzVlMDVkYjBjYSIsImVtYWlsIjoicnVqYUBob3RtYWlsLmNvbSJ9LCJpYXQiOjE2MjgzNDM3OTYsImV4cCI6MTYyODM2NTM5Nn0.jwGWAMYiF2RQhEQI74Ss6Hcfmugysa8uE2xiCKIq3CE
### Submit Cart